### ISSUE TITLE
Mobile-Menu branch issue

### ISSUE THREAD

**Issue by jkanyi-web** [yodit93/GEMS-website#1]
- Line 59 in your index.html file. Kindly don't use unused code as comment as it makes your code base unneat. Otherwise great work.
- I think it will be a good practice to style your containers outside your media queries and add the margins and padding and width values inside the media query
- I think you made a good job with this project. Just a little suggestion though, the navbar needs improvement. You may try to use display functions to make it hidden and visible.

**Comment by yodit93** [comment]
I have corrected all.
Thank you.
